development:
  adapter: mysql
  database: addicted_development
  username: root
  password:
  host: localhost
test:
  adapter: mysql
  database: addicted_test
  username: root
  password:
  host: localhost
production:
  adapter: mysql
  database: addicted
  username: root
  password:
  host: localhost